# Build inside a FreeBSD VM inside the macos VM
# https://github.com/vmactions/freebsd-vm

name: BE13_API CI (c++17) on FreeBSD
on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: make check on FreeBSD
      uses: vmactions/freebsd-vm@v0.1.4
      with:
        usesh: true
        sync: sshfs
        prepare: pkg install -y libtool libltdl automake openssl-devel pkgconf bash wget texinfo
        mem: 2048
        run: |
          wget https://ftpmirror.gnu.org/autoconf/autoconf-2.71.tar.gz
          tar xfz autoconf-2.71.tar.gz && cd autoconf-2.71 && ./configure && make && make install
          autoconf --version
          automake --version
          echo ==================================================
          echo ==================================================
          echo ls -l:
          ls -l
          echo pwd
          pwd
          echo ==================================================
          bash bootstrap.sh
          ./configure
          make check

    - name: Save failures report
      if:   failure()
      uses: actions/upload-artifact@v2
      with:
        name: freebsd-error-report
        path: |
          autom4te.cache/**
          config.log
          config.h
          test*.log

    - uses: ammaraskar/gcc-problem-matcher@0.1
      name: GCC Problem Matcher
